[package]
name = "crate-shared-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rand = "0.8"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
getrandom = "0.2"

[lib]
crate-type = ["cdylib"]
name = "crate_shared"
path = "src/lib.rs"